version: '3.8'

services:
  service_php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: service_php
    restart: unless-stopped
    ports:
      - "9000:80"
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      - SYMFONY_ENV=dev
    depends_on:
      - db
    command: >
      sh -c "
      php bin/console doctrine:schema:update --force &&
      php bin/console doctrine:fixtures:load --no-interaction &&
      php-fpm
      "

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - service_php

  db:
    image: postgres:16
    container_name: symfony_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    volumes:
      - db_data:/var/lib/postgresql/test_data
      - ./docker/postgres/pg_hba.conf:/var/lib/postgresql/test_data/pg_hba.conf
    ports:
      - "5432"

volumes:
  db_data:
